### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by mschoch** [leemcloughlin/gofarmhash#1]
Can you clarify the license under which you are releasing this port?  Preferably with a file in the repo or mention in the README.

The godocs for the repo include a copy of the original google copyright and license, but it seems this does not cover your port.

**Comment by leemcloughlin** [comment]
I've updated the README to clarify things:

License

As this is just a fairly literal port of Google's code consider this under
the same license (MIT license). For details see COPYING

Where COPYING is the license you found in the godocs documentation

Best regards

Lee McLoughlin CTO LMMR Technologies

http://uk.linkedin.com/pub/lee-mcloughlin/1/973/481

**Comment by mschoch** [comment]
Thanks
